M48
; DRILL file {KiCad 9.0.0} date 2025-09-02T15:48:58+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-02T15:48:58+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
%
G90
G05
T1
X84.1Y-45.01
T2
X84.1Y-50.79
M30
